In [23]:
import numpy

In [24]:
data = numpy.load('./../Data/shape_diameter/7_sd.npy')

In [25]:
data.shape

(82, 82, 82)

In [35]:
data[41][41]

array([0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.01364 , 0.01666 , 0.09625 ,
       0.1266  , 0.0973  , 0.0864  , 0.00568 , 0.005627, 0.0943  ,
       0.0943  , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      , 0.      , 0.      ,
       0.      , 0.      , 0.      , 0.      ], dtype=float16)

In [8]:
import sys, os
sys.path.append('./util')

In [9]:
import binvox_rw

In [13]:
with open('./../Data/vox_82/13.binvox', 'rb') as f:
    m1 = binvox_rw.read_as_3d_array(f)

In [15]:
type(m1.data)

numpy.ndarray

In [16]:
m1.data.shape

(82, 82, 82)

In [19]:
arr = [1,1,1,1,1,1,1,1,1,1,1,1, 0, 0, 0]

In [20]:
arr = numpy.array(arr)
print(arr)

[1 1 1 1 1 1 1 1 1 1 1 1 0 0 0]


In [21]:
arr = numpy.reshape(arr, (3, 5))

In [22]:
print(arr)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 0 0 0]]
